<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0G0dfh9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0G0dfh9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0G0dfh9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'cr' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'er' => ['privates', 'App\\Repository\\EnseignantRepository', 'getEnseignantRepositoryService', true],
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
            'paymentMethodRepository' => ['privates', 'App\\Repository\\PaymentMethodRepository', 'getPaymentMethodRepositoryService', true],
            'quizRepository' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
            'sluggerInterface' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'cr' => 'App\\Repository\\CoursRepository',
            'em' => '?',
            'er' => 'App\\Repository\\EnseignantRepository',
            'fileUploader' => 'App\\Service\\FileUploader',
            'paymentMethodRepository' => 'App\\Repository\\PaymentMethodRepository',
            'quizRepository' => 'App\\Repository\\QuizRepository',
            'sluggerInterface' => '?',
        ]);
    }
}
