<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VIrGozwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VIrGozw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VIrGozw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'paginatorInterface' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'paginatorInterface' => '?',
            'slugger' => '?',
        ]);
    }
}
