<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5qYIAhNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5qYIAhN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5qYIAhN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lecture' => ['privates', '.errored..service_locator.5qYIAhN.App\\Entity\\Lecture', NULL, 'Cannot autowire service ".service_locator.5qYIAhN": it needs an instance of "App\\Entity\\Lecture" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lecture' => 'App\\Entity\\Lecture',
        ]);
    }
}
