<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MI1r52cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mI1r52c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mI1r52c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sousSysteme' => ['privates', '.errored..service_locator.mI1r52c.App\\Entity\\SousSysteme', NULL, 'Cannot autowire service ".service_locator.mI1r52c": it needs an instance of "App\\Entity\\SousSysteme" but this type has been excluded in "config/services.yaml".'],
            'sousSystemeRepository' => ['privates', 'App\\Repository\\SousSystemeRepository', 'getSousSystemeRepositoryService', true],
        ], [
            'sousSysteme' => 'App\\Entity\\SousSysteme',
            'sousSystemeRepository' => 'App\\Repository\\SousSystemeRepository',
        ]);
    }
}
