<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XBu8bEJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XBu8bEJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XBu8bEJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lecture' => ['privates', '.errored..service_locator.XBu8bEJ.App\\Entity\\Lecture', NULL, 'Cannot autowire service ".service_locator.XBu8bEJ": it needs an instance of "App\\Entity\\Lecture" but this type has been excluded in "config/services.yaml".'],
            'lectureRepository' => ['privates', 'App\\Repository\\LectureRepository', 'getLectureRepositoryService', true],
            'lessonRepository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
        ], [
            'lecture' => 'App\\Entity\\Lecture',
            'lectureRepository' => 'App\\Repository\\LectureRepository',
            'lessonRepository' => 'App\\Repository\\LessonRepository',
        ]);
    }
}
