<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ep8i1lpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ep8i1lp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ep8i1lp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'filiereRepository' => ['privates', 'App\\Repository\\FiliereRepository', 'getFiliereRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'filiereRepository' => 'App\\Repository\\FiliereRepository',
            'slugger' => '?',
        ]);
    }
}
