<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IOqkD0RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iOqkD0R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iOqkD0R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'course' => ['privates', '.errored..service_locator.iOqkD0R.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.iOqkD0R": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
        ], [
            'course' => 'App\\Entity\\Cours',
        ]);
    }
}
