<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RlA3o86Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rlA3o86' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rlA3o86'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificationTemplate' => ['privates', '.errored..service_locator.rlA3o86.App\\Entity\\NotificationTemplate', NULL, 'Cannot autowire service ".service_locator.rlA3o86": it needs an instance of "App\\Entity\\NotificationTemplate" but this type has been excluded in "config/services.yaml".'],
            'notificationTemplateRepository' => ['privates', 'App\\Repository\\NotificationTemplateRepository', 'getNotificationTemplateRepositoryService', true],
        ], [
            'notificationTemplate' => 'App\\Entity\\NotificationTemplate',
            'notificationTemplateRepository' => 'App\\Repository\\NotificationTemplateRepository',
        ]);
    }
}
