<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Irtl5bFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.irtl5bF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.irtl5bF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'forum' => ['privates', '.errored..service_locator.irtl5bF.App\\Entity\\Forum', NULL, 'Cannot autowire service ".service_locator.irtl5bF": it needs an instance of "App\\Entity\\Forum" but this type has been excluded in "config/services.yaml".'],
        ], [
            'forum' => 'App\\Entity\\Forum',
        ]);
    }
}
