<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4ylJ6pPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4ylJ6pP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4ylJ6pP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evaluationQuestion' => ['privates', '.errored..service_locator.4ylJ6pP.App\\Entity\\EvaluationQuestion', NULL, 'Cannot autowire service ".service_locator.4ylJ6pP": it needs an instance of "App\\Entity\\EvaluationQuestion" but this type has been excluded in "config/services.yaml".'],
            'evaluationQuestionRepository' => ['privates', 'App\\Repository\\EvaluationQuestionRepository', 'getEvaluationQuestionRepositoryService', true],
        ], [
            'evaluationQuestion' => 'App\\Entity\\EvaluationQuestion',
            'evaluationQuestionRepository' => 'App\\Repository\\EvaluationQuestionRepository',
        ]);
    }
}
