<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AaST1nnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aaST1nn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aaST1nn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chapitre' => ['privates', '.errored..service_locator.aaST1nn.App\\Entity\\Chapitre', NULL, 'Cannot autowire service ".service_locator.aaST1nn": it needs an instance of "App\\Entity\\Chapitre" but this type has been excluded in "config/services.yaml".'],
            'chapitreRepository' => ['privates', 'App\\Repository\\ChapitreRepository', 'getChapitreRepositoryService', true],
        ], [
            'chapitre' => 'App\\Entity\\Chapitre',
            'chapitreRepository' => 'App\\Repository\\ChapitreRepository',
        ]);
    }
}
