<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G_R2VMpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G.r2VMp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G.r2VMp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'networkConfigRepository' => ['privates', 'App\\Repository\\NetworkConfigRepository', 'getNetworkConfigRepositoryService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', false],
        ], [
            'entityManager' => '?',
            'networkConfigRepository' => 'App\\Repository\\NetworkConfigRepository',
            'translator' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
