<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__PB0HcEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..PB0HcE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..PB0HcE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medium' => ['privates', '.errored..service_locator..PB0HcE.App\\Entity\\Media', NULL, 'Cannot autowire service ".service_locator..PB0HcE": it needs an instance of "App\\Entity\\Media" but this type has been excluded in "config/services.yaml".'],
        ], [
            'medium' => 'App\\Entity\\Media',
        ]);
    }
}
