<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FD6gyoRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fD6gyoR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fD6gyoR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fAQ' => ['privates', '.errored..service_locator.fD6gyoR.App\\Entity\\FAQ', NULL, 'Cannot autowire service ".service_locator.fD6gyoR": it needs an instance of "App\\Entity\\FAQ" but this type has been excluded in "config/services.yaml".'],
        ], [
            'fAQ' => 'App\\Entity\\FAQ',
        ]);
    }
}
