<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FzX53bKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fzX53bK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fzX53bK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cours' => ['privates', '.errored..service_locator.fzX53bK.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.fzX53bK": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'enseignantRepository' => ['privates', 'App\\Repository\\EnseignantRepository', 'getEnseignantRepositoryService', true],
        ], [
            'cours' => 'App\\Entity\\Cours',
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'enseignantRepository' => 'App\\Repository\\EnseignantRepository',
        ]);
    }
}
