<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6Fe3VWiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6Fe3VWi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6Fe3VWi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'forumMessage' => ['privates', '.errored..service_locator.6Fe3VWi.App\\Entity\\ForumMessage', NULL, 'Cannot autowire service ".service_locator.6Fe3VWi": it needs an instance of "App\\Entity\\ForumMessage" but this type has been excluded in "config/services.yaml".'],
            'forumMessageRepository' => ['privates', 'App\\Repository\\ForumMessageRepository', 'getForumMessageRepositoryService', true],
        ], [
            'forumMessage' => 'App\\Entity\\ForumMessage',
            'forumMessageRepository' => 'App\\Repository\\ForumMessageRepository',
        ]);
    }
}
