<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ak2dIxaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ak2dIxa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ak2dIxa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'exam' => ['privates', '.errored..service_locator.Ak2dIxa.App\\Entity\\Exam', NULL, 'Cannot autowire service ".service_locator.Ak2dIxa": it needs an instance of "App\\Entity\\Exam" but this type has been excluded in "config/services.yaml".'],
            'examRepository' => ['privates', 'App\\Repository\\ExamRepository', 'getExamRepositoryService', true],
        ], [
            'exam' => 'App\\Entity\\Exam',
            'examRepository' => 'App\\Repository\\ExamRepository',
        ]);
    }
}
