<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JpTvOfsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JpTvOfs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JpTvOfs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lesson' => ['privates', '.errored..service_locator.JpTvOfs.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.JpTvOfs": it needs an instance of "App\\Entity\\Lesson" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'lesson' => 'App\\Entity\\Lesson',
        ]);
    }
}
