<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QvyKzbrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qvyKzbr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qvyKzbr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'networkConfig' => ['privates', '.errored..service_locator.qvyKzbr.App\\Entity\\NetworkConfig', NULL, 'Cannot autowire service ".service_locator.qvyKzbr": it needs an instance of "App\\Entity\\NetworkConfig" but this type has been excluded in "config/services.yaml".'],
        ], [
            'networkConfig' => 'App\\Entity\\NetworkConfig',
        ]);
    }
}
