<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E8EBBeeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e8EBBee' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e8EBBee'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'classe' => ['privates', '.errored..service_locator.e8EBBee.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.e8EBBee": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".'],
            'classeRepository' => ['privates', 'App\\Repository\\ClasseRepository', 'getClasseRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'classe' => 'App\\Entity\\Classe',
            'classeRepository' => 'App\\Repository\\ClasseRepository',
            'slugger' => '?',
        ]);
    }
}
