<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U0am54AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u0am54A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u0am54A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'typeEnseignement' => ['privates', '.errored..service_locator.u0am54A.App\\Entity\\TypeEnseignement', NULL, 'Cannot autowire service ".service_locator.u0am54A": it needs an instance of "App\\Entity\\TypeEnseignement" but this type has been excluded in "config/services.yaml".'],
            'typeEnseignementRepository' => ['privates', 'App\\Repository\\TypeEnseignementRepository', 'getTypeEnseignementRepositoryService', true],
        ], [
            'slugger' => '?',
            'typeEnseignement' => 'App\\Entity\\TypeEnseignement',
            'typeEnseignementRepository' => 'App\\Repository\\TypeEnseignementRepository',
        ]);
    }
}
