<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WSodB8cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WSodB8c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WSodB8c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sousSystemeRepository' => ['privates', 'App\\Repository\\SousSystemeRepository', 'getSousSystemeRepositoryService', true],
        ], [
            'sousSystemeRepository' => 'App\\Repository\\SousSystemeRepository',
        ]);
    }
}
