<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kox0Cn_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kox0Cn.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kox0Cn.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'specialiteRepository' => ['privates', 'App\\Repository\\SpecialiteRepository', 'getSpecialiteRepositoryService', true],
        ], [
            'specialiteRepository' => 'App\\Repository\\SpecialiteRepository',
        ]);
    }
}
