<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapitreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LHBTlSB.App\Entity\Chapitre' shared service.
     *
     * @return \App\Entity\Chapitre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LHBTlSB": it needs an instance of "App\\Entity\\Chapitre" but this type has been excluded in "config/services.yaml".');
    }
}
