<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvaluation4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OgsBuKp.App\Entity\Evaluation' shared service.
     *
     * @return \App\Entity\Evaluation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OgsBuKp": it needs an instance of "App\\Entity\\Evaluation" but this type has been excluded in "config/services.yaml".');
    }
}
