<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLecture2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XBu8bEJ.App\Entity\Lecture' shared service.
     *
     * @return \App\Entity\Lecture
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XBu8bEJ": it needs an instance of "App\\Entity\\Lecture" but this type has been excluded in "config/services.yaml".');
    }
}
