<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\LoginSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\LoginSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/LoginSubscriber.php';

        return $container->privates['App\\EventSubscriber\\LoginSubscriber'] = new \App\EventSubscriber\LoginSubscriber(($container->privates['App\\Repository\\UserRepository'] ?? $container->getUserRepositoryService()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\PersonneRepository'] ?? $container->getPersonneRepositoryService()));
    }
}
