<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropositionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wQsOg.V.App\Entity\Proposition' shared service.
     *
     * @return \App\Entity\Proposition
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wQsOg.V": it needs an instance of "App\\Entity\\Proposition" but this type has been excluded in "config/services.yaml".');
    }
}
