<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSujet4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Qip0gkl.App\Entity\Sujet' shared service.
     *
     * @return \App\Entity\Sujet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Qip0gkl": it needs an instance of "App\\Entity\\Sujet" but this type has been excluded in "config/services.yaml".');
    }
}
