<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeEnseignementTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TypeEnseignementType' shared autowired service.
     *
     * @return \App\Form\TypeEnseignementType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TypeEnseignementType.php';

        return $container->privates['App\\Form\\TypeEnseignementType'] = new \App\Form\TypeEnseignementType();
    }
}
