<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeEnseignement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.slnpeg..App\Entity\TypeEnseignement' shared service.
     *
     * @return \App\Entity\TypeEnseignement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.slnpeg.": it needs an instance of "App\\Entity\\TypeEnseignement" but this type has been excluded in "config/services.yaml".');
    }
}
