vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        personne_avatar:
            uri_prefix: /images/eleves
            upload_destination: '%kernel.project_dir%/public/uploads/images/eleves'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        lesson_poster:
            uri_prefix: /media/courses/lessons/posters
            upload_destination: '%kernel.project_dir%/public/uploads/media/courses/lessons/posters'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        lesson_video:
            uri_prefix: /media/courses/lessons/videos
            upload_destination: '%kernel.project_dir%/public/uploads/media/courses/lessons/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        formations_path:
            uri_prefix: /media/formations/images
            upload_destination: '%kernel.project_dir%/public/uploads/media/formations/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
