<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TMKevGrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TMKevGr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TMKevGr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lesson' => ['privates', '.errored..service_locator.TMKevGr.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.TMKevGr": it needs an instance of "App\\Entity\\Lesson" but this type has been excluded in "config/services.yaml".'],
            'lessonRepository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'lesson' => 'App\\Entity\\Lesson',
            'lessonRepository' => 'App\\Repository\\LessonRepository',
            'slugger' => '?',
        ]);
    }
}
