<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DopBWqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DopB_Wq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DopB_Wq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sujet' => ['privates', '.errored..service_locator.DopB_Wq.App\\Entity\\Sujet', NULL, 'Cannot autowire service ".service_locator.DopB_Wq": it needs an instance of "App\\Entity\\Sujet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'sujet' => 'App\\Entity\\Sujet',
        ]);
    }
}
