<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8HlNKHiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8HlNKHi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8HlNKHi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'forumMessageRepository' => ['privates', 'App\\Repository\\ForumMessageRepository', 'getForumMessageRepositoryService', true],
            'membre' => ['privates', '.errored..service_locator.8HlNKHi.App\\Entity\\Membre', NULL, 'Cannot autowire service ".service_locator.8HlNKHi": it needs an instance of "App\\Entity\\Membre" but this type has been excluded in "config/services.yaml".'],
            'sujet' => ['privates', '.errored..service_locator.8HlNKHi.App\\Entity\\Sujet', NULL, 'Cannot autowire service ".service_locator.8HlNKHi": it needs an instance of "App\\Entity\\Sujet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'forumMessageRepository' => 'App\\Repository\\ForumMessageRepository',
            'membre' => 'App\\Entity\\Membre',
            'sujet' => 'App\\Entity\\Sujet',
        ]);
    }
}
