<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MqZjctService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._mqZjct' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._mqZjct'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'abonnementItemRepository' => ['privates', 'App\\Repository\\AbonnementItemRepository', 'getAbonnementItemRepositoryService', true],
        ], [
            'abonnementItemRepository' => 'App\\Repository\\AbonnementItemRepository',
        ]);
    }
}
