<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HEpB5mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H_EpB5m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H_EpB5m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'abonnement' => ['privates', '.errored..service_locator.H_EpB5m.App\\Entity\\Abonnement', NULL, 'Cannot autowire service ".service_locator.H_EpB5m": it needs an instance of "App\\Entity\\Abonnement" but this type has been excluded in "config/services.yaml".'],
            'abonnementItemRepository' => ['privates', 'App\\Repository\\AbonnementItemRepository', 'getAbonnementItemRepositoryService', true],
            'eleveRepository' => ['privates', 'App\\Repository\\EleveRepository', 'getEleveRepositoryService', true],
            'paymentMethodRepository' => ['privates', 'App\\Repository\\PaymentMethodRepository', 'getPaymentMethodRepositoryService', true],
            'paymentRepository' => ['privates', 'App\\Repository\\PaymentRepository', 'getPaymentRepositoryService', true],
        ], [
            'abonnement' => 'App\\Entity\\Abonnement',
            'abonnementItemRepository' => 'App\\Repository\\AbonnementItemRepository',
            'eleveRepository' => 'App\\Repository\\EleveRepository',
            'paymentMethodRepository' => 'App\\Repository\\PaymentMethodRepository',
            'paymentRepository' => 'App\\Repository\\PaymentRepository',
        ]);
    }
}
