<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XYRnh8FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XYRnh8F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XYRnh8F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'enseignantRepository' => ['privates', 'App\\Repository\\EnseignantRepository', 'getEnseignantRepositoryService', true],
            'networkConfigRepository' => ['privates', 'App\\Repository\\NetworkConfigRepository', 'getNetworkConfigRepositoryService', true],
            'retraitRepository' => ['privates', 'App\\Repository\\RetraitRepository', 'getRetraitRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', false],
        ], [
            'enseignantRepository' => 'App\\Repository\\EnseignantRepository',
            'networkConfigRepository' => 'App\\Repository\\NetworkConfigRepository',
            'retraitRepository' => 'App\\Repository\\RetraitRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
