<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CgbC6OrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cgbC6Or' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cgbC6Or'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formation' => ['privates', '.errored..service_locator.cgbC6Or.App\\Entity\\Formation', NULL, 'Cannot autowire service ".service_locator.cgbC6Or": it needs an instance of "App\\Entity\\Formation" but this type has been excluded in "config/services.yaml".'],
            'formationRepository' => ['privates', 'App\\Repository\\FormationRepository', 'getFormationRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'formation' => 'App\\Entity\\Formation',
            'formationRepository' => 'App\\Repository\\FormationRepository',
            'slugger' => '?',
        ]);
    }
}
