<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MAe8GY_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mAe8GY.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mAe8GY.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eleve' => ['privates', '.errored..service_locator.mAe8GY..App\\Entity\\Eleve', NULL, 'Cannot autowire service ".service_locator.mAe8GY.": it needs an instance of "App\\Entity\\Eleve" but this type has been excluded in "config/services.yaml".'],
            'lecture' => ['privates', '.errored..service_locator.mAe8GY..App\\Entity\\Lecture', NULL, 'Cannot autowire service ".service_locator.mAe8GY.": it needs an instance of "App\\Entity\\Lecture" but this type has been excluded in "config/services.yaml".'],
        ], [
            'eleve' => 'App\\Entity\\Eleve',
            'lecture' => 'App\\Entity\\Lecture',
        ]);
    }
}
