<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZJUkcDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zJUkcD_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zJUkcD_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cours' => ['privates', '.errored..service_locator.zJUkcD_.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.zJUkcD_": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'eleveRepository' => ['privates', 'App\\Repository\\EleveRepository', 'getEleveRepositoryService', true],
            'lectureRepository' => ['privates', 'App\\Repository\\LectureRepository', 'getLectureRepositoryService', true],
            'lessonRepository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
            'membreRepository' => ['privates', 'App\\Repository\\MembreRepository', 'getMembreRepositoryService', true],
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
        ], [
            'cours' => 'App\\Entity\\Cours',
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'eleveRepository' => 'App\\Repository\\EleveRepository',
            'lectureRepository' => 'App\\Repository\\LectureRepository',
            'lessonRepository' => 'App\\Repository\\LessonRepository',
            'membreRepository' => 'App\\Repository\\MembreRepository',
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
        ]);
    }
}
