<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UVTlCsZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UVTlCsZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UVTlCsZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'forum' => ['privates', '.errored..service_locator.UVTlCsZ.App\\Entity\\Forum', NULL, 'Cannot autowire service ".service_locator.UVTlCsZ": it needs an instance of "App\\Entity\\Forum" but this type has been excluded in "config/services.yaml".'],
            'forumRepository' => ['privates', 'App\\Repository\\ForumRepository', 'getForumRepositoryService', true],
        ], [
            'forum' => 'App\\Entity\\Forum',
            'forumRepository' => 'App\\Repository\\ForumRepository',
        ]);
    }
}
