<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GXW8MDBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GXW8MDB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GXW8MDB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formation' => ['privates', '.errored..service_locator.GXW8MDB.App\\Entity\\Formation', NULL, 'Cannot autowire service ".service_locator.GXW8MDB": it needs an instance of "App\\Entity\\Formation" but this type has been excluded in "config/services.yaml".'],
            'formationRepository' => ['privates', 'App\\Repository\\FormationRepository', 'getFormationRepositoryService', true],
        ], [
            'formation' => 'App\\Entity\\Formation',
            'formationRepository' => 'App\\Repository\\FormationRepository',
        ]);
    }
}
