<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LzG3dgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lz_g3dg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lz_g3dg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'abonnementRepository' => ['privates', 'App\\Repository\\AbonnementRepository', 'getAbonnementRepositoryService', true],
            'sluggerInterface' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'abonnementRepository' => 'App\\Repository\\AbonnementRepository',
            'sluggerInterface' => '?',
        ]);
    }
}
