<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UlCPoMTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UlCPoMT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UlCPoMT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'forumMessage' => ['privates', '.errored..service_locator.UlCPoMT.App\\Entity\\ForumMessage', NULL, 'Cannot autowire service ".service_locator.UlCPoMT": it needs an instance of "App\\Entity\\ForumMessage" but this type has been excluded in "config/services.yaml".'],
            'forumMessageRepository' => ['privates', 'App\\Repository\\ForumMessageRepository', 'getForumMessageRepositoryService', true],
            'likeMessageForumRepository' => ['privates', 'App\\Repository\\LikeMessageForumRepository', 'getLikeMessageForumRepositoryService', true],
            'membreRepository' => ['privates', 'App\\Repository\\MembreRepository', 'getMembreRepositoryService', true],
        ], [
            'em' => '?',
            'forumMessage' => 'App\\Entity\\ForumMessage',
            'forumMessageRepository' => 'App\\Repository\\ForumMessageRepository',
            'likeMessageForumRepository' => 'App\\Repository\\LikeMessageForumRepository',
            'membreRepository' => 'App\\Repository\\MembreRepository',
        ]);
    }
}
