<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IHmhRtrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IHmhRtr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IHmhRtr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evaluation' => ['privates', '.errored..service_locator.IHmhRtr.App\\Entity\\Evaluation', NULL, 'Cannot autowire service ".service_locator.IHmhRtr": it needs an instance of "App\\Entity\\Evaluation" but this type has been excluded in "config/services.yaml".'],
            'evaluationQuestionRepository' => ['privates', 'App\\Repository\\EvaluationQuestionRepository', 'getEvaluationQuestionRepositoryService', true],
        ], [
            'evaluation' => 'App\\Entity\\Evaluation',
            'evaluationQuestionRepository' => 'App\\Repository\\EvaluationQuestionRepository',
        ]);
    }
}
