<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q2J1hJrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q2J1hJr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q2J1hJr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'enseignant' => ['privates', '.errored..service_locator.Q2J1hJr.App\\Entity\\Enseignant', NULL, 'Cannot autowire service ".service_locator.Q2J1hJr": it needs an instance of "App\\Entity\\Enseignant" but this type has been excluded in "config/services.yaml".'],
            'paginatorInterface' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
        ], [
            'enseignant' => 'App\\Entity\\Enseignant',
            'paginatorInterface' => '?',
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
        ]);
    }
}
