<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EgHX0z5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EgHX0z5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EgHX0z5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'forumRepository' => ['privates', 'App\\Repository\\ForumRepository', 'getForumRepositoryService', true],
            'paginatorInterface' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'sujetRepository' => ['privates', 'App\\Repository\\SujetRepository', 'getSujetRepositoryService', true],
        ], [
            'forumRepository' => 'App\\Repository\\ForumRepository',
            'paginatorInterface' => '?',
            'sujetRepository' => 'App\\Repository\\SujetRepository',
        ]);
    }
}
