<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WQsOg_VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wQsOg.V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wQsOg.V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'proposition' => ['privates', '.errored..service_locator.wQsOg.V.App\\Entity\\Proposition', NULL, 'Cannot autowire service ".service_locator.wQsOg.V": it needs an instance of "App\\Entity\\Proposition" but this type has been excluded in "config/services.yaml".'],
        ], [
            'proposition' => 'App\\Entity\\Proposition',
        ]);
    }
}
