<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NuHUyxgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nuHUyxg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nuHUyxg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'filiere' => ['privates', '.errored..service_locator.nuHUyxg.App\\Entity\\Filiere', NULL, 'Cannot autowire service ".service_locator.nuHUyxg": it needs an instance of "App\\Entity\\Filiere" but this type has been excluded in "config/services.yaml".'],
        ], [
            'filiere' => 'App\\Entity\\Filiere',
        ]);
    }
}
