<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0yBt7AvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0yBt7Av' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0yBt7Av'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mediaRepository' => ['privates', 'App\\Repository\\MediaRepository', 'getMediaRepositoryService', true],
            'medium' => ['privates', '.errored..service_locator.0yBt7Av.App\\Entity\\Media', NULL, 'Cannot autowire service ".service_locator.0yBt7Av": it needs an instance of "App\\Entity\\Media" but this type has been excluded in "config/services.yaml".'],
        ], [
            'mediaRepository' => 'App\\Repository\\MediaRepository',
            'medium' => 'App\\Entity\\Media',
        ]);
    }
}
