<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HMsaM1zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HMsaM1z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HMsaM1z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificationRepository' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', true],
            'review' => ['privates', '.errored..service_locator.HMsaM1z.App\\Entity\\Review', NULL, 'Cannot autowire service ".service_locator.HMsaM1z": it needs an instance of "App\\Entity\\Review" but this type has been excluded in "config/services.yaml".'],
        ], [
            'notificationRepository' => 'App\\Repository\\NotificationRepository',
            'review' => 'App\\Entity\\Review',
        ]);
    }
}
