<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCours15Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iOqkD0R.App\Entity\Cours' shared service.
     *
     * @return \App\Entity\Cours
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iOqkD0R": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".');
    }
}
