<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChangeAvatarControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Controller\User\ChangeAvatarController' shared autowired service.
     *
     * @return \App\Controller\Api\Controller\User\ChangeAvatarController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'ChangeAvatarController.php';

        return $container->services['App\\Controller\\Api\\Controller\\User\\ChangeAvatarController'] = new \App\Controller\Api\Controller\User\ChangeAvatarController();
    }
}
