<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrdersControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\IInstructor\OrdersController' shared autowired service.
     *
     * @return \App\Controller\IInstructor\OrdersController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'IInstructor'.\DIRECTORY_SEPARATOR.'OrdersController.php';

        $container->services['App\\Controller\\IInstructor\\OrdersController'] = $instance = new \App\Controller\IInstructor\OrdersController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\IInstructor\\OrdersController', $container));

        return $instance;
    }
}
