<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Controller\Course\Quiz\PostController' shared autowired service.
     *
     * @return \App\Controller\Api\Controller\Course\Quiz\PostController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Course'.\DIRECTORY_SEPARATOR.'Quiz'.\DIRECTORY_SEPARATOR.'PostController.php';

        $container->services['App\\Controller\\Api\\Controller\\Course\\Quiz\\PostController'] = $instance = new \App\Controller\Api\Controller\Course\Quiz\PostController(($container->privates['App\\Repository\\EleveRepository'] ?? $container->load('getEleveRepositoryService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')), ($container->privates['App\\Repository\\ChapitreRepository'] ?? $container->load('getChapitreRepositoryService')), ($container->privates['App\\Repository\\QuizLostRepository'] ?? $container->load('getQuizLostRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\LectureRepository'] ?? $container->load('getLectureRepositoryService')), ($container->privates['App\\Repository\\QuizResultRepository'] ?? $container->load('getQuizResultRepositoryService')), ($container->privates['App\\Repository\\QuizRepository'] ?? $container->load('getQuizRepositoryService')), ($container->privates['App\\Repository\\CoursRepository'] ?? $container->load('getCoursRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\Api\\Controller\\Course\\Quiz\\PostController', $container));

        return $instance;
    }
}
