<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSousSysteme3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mI1r52c.App\Entity\SousSysteme' shared service.
     *
     * @return \App\Entity\SousSysteme
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mI1r52c": it needs an instance of "App\\Entity\\SousSysteme" but this type has been excluded in "config/services.yaml".');
    }
}
