<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'user_listener' shared autowired service.
     *
     * @return \App\EntityListener\UserListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EntityListener'.\DIRECTORY_SEPARATOR.'UserListener.php';

        $a = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['user_listener'])) {
            return $container->privates['user_listener'];
        }
        $b = ($container->privates['App\\Security\\EmailVerifier'] ?? $container->load('getEmailVerifierService'));

        if (isset($container->privates['user_listener'])) {
            return $container->privates['user_listener'];
        }

        return $container->privates['user_listener'] = new \App\EntityListener\UserListener(($container->privates['App\\Repository\\PersonneRepository'] ?? $container->getPersonneRepositoryService()), $a, $b, ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
