api_refresh_token:
    path: /api/token/refresh
api_login_check:
    path: /api/login_check    
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Chat routes
chat:
    path: /chat
    controller: App\Controller\ChatController::index

chat_teachers:
    path: /chat/teachers
    controller: App\Controller\ChatController::teacherChat
