api_refresh_token:
    path: /api/token/refresh
api_login_check:
    path: /api/login_check    
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Chat routes
app_chat:
    path: /chat
    controller: App\Controller\ChatController::index

app_subject_chat:
    path: /chat/subject/{subject}
    controller: App\Controller\ChatController::subjectChat
