<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VDXxjXdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VDXxjXd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VDXxjXd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eleveRepository' => ['privates', 'App\\Repository\\EleveRepository', 'getEleveRepositoryService', true],
            'evaluation' => ['privates', '.errored..service_locator.VDXxjXd.App\\Entity\\Evaluation', NULL, 'Cannot autowire service ".service_locator.VDXxjXd": it needs an instance of "App\\Entity\\Evaluation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'eleveRepository' => 'App\\Repository\\EleveRepository',
            'evaluation' => 'App\\Entity\\Evaluation',
        ]);
    }
}
