<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O4Tpc7iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O4Tpc7i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O4Tpc7i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cours' => ['privates', '.errored..service_locator.O4Tpc7i.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.O4Tpc7i": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'eleveRepository' => ['privates', 'App\\Repository\\EleveRepository', 'getEleveRepositoryService', true],
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
        ], [
            'cours' => 'App\\Entity\\Cours',
            'eleveRepository' => 'App\\Repository\\EleveRepository',
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
        ]);
    }
}
