<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R0BjQkuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r0BjQku' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r0BjQku'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eleve' => ['privates', '.errored..service_locator.r0BjQku.App\\Entity\\Eleve', NULL, 'Cannot autowire service ".service_locator.r0BjQku": it needs an instance of "App\\Entity\\Eleve" but this type has been excluded in "config/services.yaml".'],
            'eleveRepository' => ['privates', 'App\\Repository\\EleveRepository', 'getEleveRepositoryService', true],
        ], [
            'eleve' => 'App\\Entity\\Eleve',
            'eleveRepository' => 'App\\Repository\\EleveRepository',
        ]);
    }
}
