<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HcAqDTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HcAqD_t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HcAqD_t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', '.errored..service_locator.HcAqD_t.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.HcAqD_t": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded in "config/services.yaml".'],
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'fileUploader' => 'App\\Service\\FileUploader',
            'slugger' => '?',
        ]);
    }
}
