<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XjchgF8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xjchgF8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xjchgF8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'proposition' => ['privates', '.errored..service_locator.xjchgF8.App\\Entity\\Proposition', NULL, 'Cannot autowire service ".service_locator.xjchgF8": it needs an instance of "App\\Entity\\Proposition" but this type has been excluded in "config/services.yaml".'],
            'propositionRepository' => ['privates', 'App\\Repository\\PropositionRepository', 'getPropositionRepositoryService', true],
        ], [
            'proposition' => 'App\\Entity\\Proposition',
            'propositionRepository' => 'App\\Repository\\PropositionRepository',
        ]);
    }
}
