<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SvV89WQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SvV89WQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SvV89WQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etablissement' => ['privates', '.errored..service_locator.SvV89WQ.App\\Entity\\Etablissement', NULL, 'Cannot autowire service ".service_locator.SvV89WQ": it needs an instance of "App\\Entity\\Etablissement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'etablissement' => 'App\\Entity\\Etablissement',
        ]);
    }
}
