<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JYs6EHzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JYs6EHz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JYs6EHz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'abonnementItem' => ['privates', '.errored..service_locator.JYs6EHz.App\\Entity\\AbonnementItem', NULL, 'Cannot autowire service ".service_locator.JYs6EHz": it needs an instance of "App\\Entity\\AbonnementItem" but this type has been excluded in "config/services.yaml".'],
        ], [
            'abonnementItem' => 'App\\Entity\\AbonnementItem',
        ]);
    }
}
