<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T9a0IK5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T9a0IK5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T9a0IK5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'personne' => ['privates', '.errored..service_locator.T9a0IK5.App\\Entity\\Personne', NULL, 'Cannot autowire service ".service_locator.T9a0IK5": it needs an instance of "App\\Entity\\Personne" but this type has been excluded in "config/services.yaml".'],
            'personneRepository' => ['privates', 'App\\Repository\\PersonneRepository', 'getPersonneRepositoryService', false],
        ], [
            'personne' => 'App\\Entity\\Personne',
            'personneRepository' => 'App\\Repository\\PersonneRepository',
        ]);
    }
}
