<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LCKoqJUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LCKoqJU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LCKoqJU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sujet' => ['privates', '.errored..service_locator.LCKoqJU.App\\Entity\\Sujet', NULL, 'Cannot autowire service ".service_locator.LCKoqJU": it needs an instance of "App\\Entity\\Sujet" but this type has been excluded in "config/services.yaml".'],
            'sujetRepository' => ['privates', 'App\\Repository\\SujetRepository', 'getSujetRepositoryService', true],
        ], [
            'sujet' => 'App\\Entity\\Sujet',
            'sujetRepository' => 'App\\Repository\\SujetRepository',
        ]);
    }
}
