<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SlXkoU4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SlXkoU4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SlXkoU4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lessonRepository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'lessonRepository' => 'App\\Repository\\LessonRepository',
            'slugger' => '?',
        ]);
    }
}
