<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W6TLtL4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w6TLtL4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w6TLtL4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'forumMessage' => ['privates', '.errored..service_locator.w6TLtL4.App\\Entity\\ForumMessage', NULL, 'Cannot autowire service ".service_locator.w6TLtL4": it needs an instance of "App\\Entity\\ForumMessage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'forumMessage' => 'App\\Entity\\ForumMessage',
        ]);
    }
}
