<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TGxlRXCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tGxlRXC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tGxlRXC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cour' => ['privates', '.errored..service_locator.tGxlRXC.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.tGxlRXC": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'cour' => 'App\\Entity\\Cours',
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'slugger' => '?',
        ]);
    }
}
