<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZMkT7yZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zMkT7yZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zMkT7yZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eleve' => ['privates', '.errored..service_locator.zMkT7yZ.App\\Entity\\Eleve', NULL, 'Cannot autowire service ".service_locator.zMkT7yZ": it needs an instance of "App\\Entity\\Eleve" but this type has been excluded in "config/services.yaml".'],
        ], [
            'eleve' => 'App\\Entity\\Eleve',
        ]);
    }
}
