<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DBp52GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DBp52_G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DBp52_G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evaluationRepository' => ['privates', 'App\\Repository\\EvaluationRepository', 'getEvaluationRepositoryService', false],
            'sluggerInterface' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'evaluationRepository' => 'App\\Repository\\EvaluationRepository',
            'sluggerInterface' => '?',
        ]);
    }
}
