<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RBosDZzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RBosDZz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RBosDZz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chapitre' => ['privates', '.errored..service_locator.RBosDZz.App\\Entity\\Chapitre', NULL, 'Cannot autowire service ".service_locator.RBosDZz": it needs an instance of "App\\Entity\\Chapitre" but this type has been excluded in "config/services.yaml".'],
            'quizRepository' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
        ], [
            'chapitre' => 'App\\Entity\\Chapitre',
            'quizRepository' => 'App\\Repository\\QuizRepository',
        ]);
    }
}
