<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.22DT_tw.App\Entity\Exam' shared service.
     *
     * @return \App\Entity\Exam
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.22DT_tw": it needs an instance of "App\\Entity\\Exam" but this type has been excluded in "config/services.yaml".');
    }
}
