<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFAQ2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fD6gyoR.App\Entity\FAQ' shared service.
     *
     * @return \App\Entity\FAQ
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fD6gyoR": it needs an instance of "App\\Entity\\FAQ" but this type has been excluded in "config/services.yaml".');
    }
}
