<?php

namespace ContainerBtikz0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedia2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0yBt7Av.App\Entity\Media' shared service.
     *
     * @return \App\Entity\Media
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0yBt7Av": it needs an instance of "App\\Entity\\Media" but this type has been excluded in "config/services.yaml".');
    }
}
