<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LHBTlSBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LHBTlSB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LHBTlSB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chapitre' => ['privates', '.errored..service_locator.LHBTlSB.App\\Entity\\Chapitre', NULL, 'Cannot autowire service ".service_locator.LHBTlSB": it needs an instance of "App\\Entity\\Chapitre" but this type has been excluded in "config/services.yaml".'],
            'chapitreRepository' => ['privates', 'App\\Repository\\ChapitreRepository', 'getChapitreRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'chapitre' => 'App\\Entity\\Chapitre',
            'chapitreRepository' => 'App\\Repository\\ChapitreRepository',
            'slugger' => '?',
        ]);
    }
}
