<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CIzlWojService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cIzlWoj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cIzlWoj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fAQ' => ['privates', '.errored..service_locator.cIzlWoj.App\\Entity\\FAQ', NULL, 'Cannot autowire service ".service_locator.cIzlWoj": it needs an instance of "App\\Entity\\FAQ" but this type has been excluded in "config/services.yaml".'],
            'fAQRepository' => ['privates', 'App\\Repository\\FAQRepository', 'getFAQRepositoryService', true],
        ], [
            'fAQ' => 'App\\Entity\\FAQ',
            'fAQRepository' => 'App\\Repository\\FAQRepository',
        ]);
    }
}
