<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TSnRecjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tSnRecj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tSnRecj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificationTemplate' => ['privates', '.errored..service_locator.tSnRecj.App\\Entity\\NotificationTemplate', NULL, 'Cannot autowire service ".service_locator.tSnRecj": it needs an instance of "App\\Entity\\NotificationTemplate" but this type has been excluded in "config/services.yaml".'],
        ], [
            'notificationTemplate' => 'App\\Entity\\NotificationTemplate',
        ]);
    }
}
