<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GMvq5pNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gMvq5pN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gMvq5pN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'course' => ['privates', '.errored..service_locator.gMvq5pN.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.gMvq5pN": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'paginatorInterface' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'course' => 'App\\Entity\\Cours',
            'paginatorInterface' => '?',
        ]);
    }
}
