<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JBkrMmKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JBkrMmK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JBkrMmK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'networkConfig' => ['privates', '.errored..service_locator.JBkrMmK.App\\Entity\\NetworkConfig', NULL, 'Cannot autowire service ".service_locator.JBkrMmK": it needs an instance of "App\\Entity\\NetworkConfig" but this type has been excluded in "config/services.yaml".'],
            'networkConfigRepository' => ['privates', 'App\\Repository\\NetworkConfigRepository', 'getNetworkConfigRepositoryService', true],
        ], [
            'networkConfig' => 'App\\Entity\\NetworkConfig',
            'networkConfigRepository' => 'App\\Repository\\NetworkConfigRepository',
        ]);
    }
}
