<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W4GY4t1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w4GY4t1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w4GY4t1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'enseignantRepository' => ['privates', 'App\\Repository\\EnseignantRepository', 'getEnseignantRepositoryService', true],
            'quiz' => ['privates', '.errored..service_locator.w4GY4t1.App\\Entity\\Quiz', NULL, 'Cannot autowire service ".service_locator.w4GY4t1": it needs an instance of "App\\Entity\\Quiz" but this type has been excluded in "config/services.yaml".'],
            'quizRepository' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
        ], [
            'enseignantRepository' => 'App\\Repository\\EnseignantRepository',
            'quiz' => 'App\\Entity\\Quiz',
            'quizRepository' => 'App\\Repository\\QuizRepository',
        ]);
    }
}
