<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_22DTTwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.22DT_tw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.22DT_tw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'exam' => ['privates', '.errored..service_locator.22DT_tw.App\\Entity\\Exam', NULL, 'Cannot autowire service ".service_locator.22DT_tw": it needs an instance of "App\\Entity\\Exam" but this type has been excluded in "config/services.yaml".'],
            'personneRepository' => ['privates', 'App\\Repository\\PersonneRepository', 'getPersonneRepositoryService', false],
        ], [
            'exam' => 'App\\Entity\\Exam',
            'personneRepository' => 'App\\Repository\\PersonneRepository',
        ]);
    }
}
