<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VTR_B54Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vTR.b54' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vTR.b54'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pay' => ['privates', '.errored..service_locator.vTR.b54.App\\Entity\\Pays', NULL, 'Cannot autowire service ".service_locator.vTR.b54": it needs an instance of "App\\Entity\\Pays" but this type has been excluded in "config/services.yaml".'],
            'paysRepository' => ['privates', 'App\\Repository\\PaysRepository', 'getPaysRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'pay' => 'App\\Entity\\Pays',
            'paysRepository' => 'App\\Repository\\PaysRepository',
            'slugger' => '?',
        ]);
    }
}
