<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEleve4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zMkT7yZ.App\Entity\Eleve' shared service.
     *
     * @return \App\Entity\Eleve
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zMkT7yZ": it needs an instance of "App\\Entity\\Eleve" but this type has been excluded in "config/services.yaml".');
    }
}
