<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinishedControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Controller\Course\Lesson\FinishedController' shared autowired service.
     *
     * @return \App\Controller\Api\Controller\Course\Lesson\FinishedController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Course'.\DIRECTORY_SEPARATOR.'Lesson'.\DIRECTORY_SEPARATOR.'FinishedController.php';

        $container->services['App\\Controller\\Api\\Controller\\Course\\Lesson\\FinishedController'] = $instance = new \App\Controller\Api\Controller\Course\Lesson\FinishedController(($container->privates['App\\Repository\\EleveRepository'] ?? $container->load('getEleveRepositoryService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')), ($container->privates['App\\Repository\\MembreRepository'] ?? $container->load('getMembreRepositoryService')), ($container->privates['App\\Repository\\ForumRepository'] ?? $container->load('getForumRepositoryService')), ($container->privates['App\\Repository\\LectureRepository'] ?? $container->load('getLectureRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\LessonRepository'] ?? $container->load('getLessonRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\Api\\Controller\\Course\\Lesson\\FinishedController', $container));

        return $instance;
    }
}
