<?php

namespace ContainerV9T8ODm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecialite3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oDD2JWx.App\Entity\Specialite' shared service.
     *
     * @return \App\Entity\Specialite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oDD2JWx": it needs an instance of "App\\Entity\\Specialite" but this type has been excluded in "config/services.yaml".');
    }
}
