<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'eleve' => [parent::class, 'eleve', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'enseignant' => [parent::class, 'enseignant', null],
        "\0".parent::class."\0".'especes' => [parent::class, 'especes', null],
        "\0".parent::class."\0".'exams' => [parent::class, 'exams', null],
        "\0".parent::class."\0".'filieres' => [parent::class, 'filieres', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isAdmin' => [parent::class, 'isAdmin', null],
        "\0".parent::class."\0".'isBlocked' => [parent::class, 'isBlocked', null],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null],
        "\0".parent::class."\0".'likes' => [parent::class, 'likes', null],
        "\0".parent::class."\0".'notificationSettings' => [parent::class, 'notificationSettings', null],
        "\0".parent::class."\0".'notifications' => [parent::class, 'notifications', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'personne' => [parent::class, 'personne', null],
        "\0".parent::class."\0".'points' => [parent::class, 'points', null],
        "\0".parent::class."\0".'retraits' => [parent::class, 'retraits', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        'eleve' => [parent::class, 'eleve', null],
        'email' => [parent::class, 'email', null],
        'enseignant' => [parent::class, 'enseignant', null],
        'especes' => [parent::class, 'especes', null],
        'exams' => [parent::class, 'exams', null],
        'filieres' => [parent::class, 'filieres', null],
        'id' => [parent::class, 'id', null],
        'isAdmin' => [parent::class, 'isAdmin', null],
        'isBlocked' => [parent::class, 'isBlocked', null],
        'isVerified' => [parent::class, 'isVerified', null],
        'likes' => [parent::class, 'likes', null],
        'notificationSettings' => [parent::class, 'notificationSettings', null],
        'notifications' => [parent::class, 'notifications', null],
        'parentCode' => [parent::class, 'parentCode', null],
        'password' => [parent::class, 'password', null],
        'personne' => [parent::class, 'personne', null],
        'points' => [parent::class, 'points', null],
        'retraits' => [parent::class, 'retraits', null],
        'roles' => [parent::class, 'roles', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            'parentCode' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
