<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personne extends \App\Entity\Personne implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'avatar' => [parent::class, 'avatar', null],
        "\0".parent::class."\0".'bornAt' => [parent::class, 'bornAt', null],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageFile' => [parent::class, 'imageFile', null],
        "\0".parent::class."\0".'invitationCode' => [parent::class, 'invitationCode', null],
        "\0".parent::class."\0".'invitationLink' => [parent::class, 'invitationLink', null],
        "\0".parent::class."\0".'invites' => [parent::class, 'invites', null],
        "\0".parent::class."\0".'joinAt' => [parent::class, 'joinAt', null],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null],
        "\0".parent::class."\0".'lieuNaissance' => [parent::class, 'lieuNaissance', null],
        "\0".parent::class."\0".'parent' => [parent::class, 'parent', null],
        "\0".parent::class."\0".'pays' => [parent::class, 'pays', null],
        "\0".parent::class."\0".'pseudo' => [parent::class, 'pseudo', null],
        "\0".parent::class."\0".'sexe' => [parent::class, 'sexe', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        "\0".parent::class."\0".'updateAt' => [parent::class, 'updateAt', null],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null],
        'adresse' => [parent::class, 'adresse', null],
        'avatar' => [parent::class, 'avatar', null],
        'bornAt' => [parent::class, 'bornAt', null],
        'contentUrl' => [parent::class, 'contentUrl', null],
        'file' => [parent::class, 'file', null],
        'firstName' => [parent::class, 'firstName', null],
        'id' => [parent::class, 'id', null],
        'imageFile' => [parent::class, 'imageFile', null],
        'invitationCode' => [parent::class, 'invitationCode', null],
        'invitationLink' => [parent::class, 'invitationLink', null],
        'invites' => [parent::class, 'invites', null],
        'joinAt' => [parent::class, 'joinAt', null],
        'lastName' => [parent::class, 'lastName', null],
        'lieuNaissance' => [parent::class, 'lieuNaissance', null],
        'parent' => [parent::class, 'parent', null],
        'pays' => [parent::class, 'pays', null],
        'pseudo' => [parent::class, 'pseudo', null],
        'sexe' => [parent::class, 'sexe', null],
        'telephone' => [parent::class, 'telephone', null],
        'updateAt' => [parent::class, 'updateAt', null],
        'utilisateur' => [parent::class, 'utilisateur', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            "\0".parent::class."\0".'imageFile' => true,
            'contentUrl' => true,
            'file' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
