<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Enseignant extends \App\Entity\Enseignant implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'aboutMe' => [parent::class, 'aboutMe', null],
        "\0".parent::class."\0".'cours' => [parent::class, 'cours', null],
        "\0".parent::class."\0".'details' => [parent::class, 'details', null],
        "\0".parent::class."\0".'diplome' => [parent::class, 'diplome', null],
        "\0".parent::class."\0".'discipline' => [parent::class, 'discipline', null],
        "\0".parent::class."\0".'emploiDuTemps' => [parent::class, 'emploiDuTemps', null],
        "\0".parent::class."\0".'etablissement' => [parent::class, 'etablissement', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isCertified' => [parent::class, 'isCertified', null],
        "\0".parent::class."\0".'isRejected' => [parent::class, 'isRejected', null],
        "\0".parent::class."\0".'isValidated' => [parent::class, 'isValidated', null],
        "\0".parent::class."\0".'joinAt' => [parent::class, 'joinAt', null],
        "\0".parent::class."\0".'rectoCNI' => [parent::class, 'rectoCNI', null],
        "\0".parent::class."\0".'reference' => [parent::class, 'reference', null],
        "\0".parent::class."\0".'review' => [parent::class, 'review', null],
        "\0".parent::class."\0".'selfieCNI' => [parent::class, 'selfieCNI', null],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null],
        "\0".parent::class."\0".'versoCNI' => [parent::class, 'versoCNI', null],
        'aboutMe' => [parent::class, 'aboutMe', null],
        'cours' => [parent::class, 'cours', null],
        'details' => [parent::class, 'details', null],
        'diplome' => [parent::class, 'diplome', null],
        'diplomeFile' => [parent::class, 'diplomeFile', null],
        'discipline' => [parent::class, 'discipline', null],
        'emploiDuTemps' => [parent::class, 'emploiDuTemps', null],
        'emploiDuTempsFile' => [parent::class, 'emploiDuTempsFile', null],
        'etablissement' => [parent::class, 'etablissement', null],
        'id' => [parent::class, 'id', null],
        'isCertified' => [parent::class, 'isCertified', null],
        'isRejected' => [parent::class, 'isRejected', null],
        'isValidated' => [parent::class, 'isValidated', null],
        'joinAt' => [parent::class, 'joinAt', null],
        'rectoCNI' => [parent::class, 'rectoCNI', null],
        'rectoCNIFile' => [parent::class, 'rectoCNIFile', null],
        'reference' => [parent::class, 'reference', null],
        'review' => [parent::class, 'review', null],
        'selfieCNI' => [parent::class, 'selfieCNI', null],
        'selfieCNIFile' => [parent::class, 'selfieCNIFile', null],
        'utilisateur' => [parent::class, 'utilisateur', null],
        'versoCNI' => [parent::class, 'versoCNI', null],
        'versoCNIFile' => [parent::class, 'versoCNIFile', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            'diplomeFile' => true,
            'emploiDuTempsFile' => true,
            'rectoCNIFile' => true,
            'selfieCNIFile' => true,
            'versoCNIFile' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
