<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categorie extends \App\Entity\Categorie implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'category' => [parent::class, 'category', null],
        "\0".parent::class."\0".'cours' => [parent::class, 'cours', null],
        "\0".parent::class."\0".'enseignants' => [parent::class, 'enseignants', null],
        "\0".parent::class."\0".'evaluations' => [parent::class, 'evaluations', null],
        "\0".parent::class."\0".'exams' => [parent::class, 'exams', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageFile' => [parent::class, 'imageFile', null],
        "\0".parent::class."\0".'isSubCategory' => [parent::class, 'isSubCategory', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'subCategories' => [parent::class, 'subCategories', null],
        'category' => [parent::class, 'category', null],
        'cours' => [parent::class, 'cours', null],
        'enseignants' => [parent::class, 'enseignants', null],
        'evaluations' => [parent::class, 'evaluations', null],
        'exams' => [parent::class, 'exams', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'imageFile' => [parent::class, 'imageFile', null],
        'isSubCategory' => [parent::class, 'isSubCategory', null],
        'name' => [parent::class, 'name', null],
        'slug' => [parent::class, 'slug', null],
        'subCategories' => [parent::class, 'subCategories', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            'image' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
